






















#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;
using Sitecore.Data.Items;
using SystemSpecialized = System.Collections.Specialized;



namespace TresDivas.Website.Models
{

    public partial interface IGlassBase{
        
        [SitecoreId]
        Guid Id{ get; }

        [SitecoreInfo(SitecoreInfoType.Name)]
        string ItemName { get; }

        [SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

        [SitecoreInfo(SitecoreInfoType.Url)]
        string Url { get; }

        [SitecoreInfo(SitecoreInfoType.Path)]
        string Path { get; set; }

        [SitecoreInfo(SitecoreInfoType.TemplateId)]
        Guid TemplateId { get; set; }

        [SitecoreInfo(SitecoreInfoType.TemplateName)]
        string TemplateName { get; set; }

        [SitecoreItem]
        Item Item { get; }
    }

    public abstract partial class GlassBase : IGlassBase{
        
        [SitecoreId]
        public virtual Guid Id{ get; private set;}

        [SitecoreInfo(SitecoreInfoType.Name)]
        public string ItemName { get; private set; }

        [SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

        [SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }

        [SitecoreInfo(SitecoreInfoType.Path)]
        public virtual string Path { get; set; }

        [SitecoreInfo(SitecoreInfoType.TemplateId)]
        public Guid TemplateId { get; set; }

        [SitecoreInfo(SitecoreInfoType.TemplateName)]
        public string TemplateName { get; set; }

        [SitecoreItem]
        public virtual Item Item { get; private set; }
    }
}
namespace TresDivas.Website.Models.sitecore.templates.Project.TresDivas.Modules
{


 	/// <summary>
	/// IProduct_Details Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/TresDivas/Modules/Product Details</para>	
	/// <para>ID: 13cf5071-f642-4639-aec7-b45a29c939c4</para>	
	/// </summary>
	[SitecoreType(TemplateId=IProduct_DetailsConstants.TemplateIdString )] //, Cachable = true
	public partial interface IProduct_Details : IGlassBase 
	{
			
					/// <summary>
					/// The Bagel Function field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: b9c46a24-959a-41fd-a697-65c341a132f1</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IProduct_DetailsConstants.Bagel_FunctionFieldName)]
					string Bagel_Function  {get; set;}
			
			
					/// <summary>
					/// The Description field.
					/// <para></para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: 0f663071-efe6-4c41-b09b-ff5137d7b379</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IProduct_DetailsConstants.DescriptionFieldName)]
					string Description  {get; set;}
			
			
					/// <summary>
					/// The Extra Lift field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: e7971b67-73c0-4bf3-a3fd-d2a85a226ef7</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IProduct_DetailsConstants.Extra_LiftFieldName)]
					string Extra_Lift  {get; set;}
			
			
					/// <summary>
					/// The Product Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: db0e3e15-dc51-4075-865a-0084c20c854d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IProduct_DetailsConstants.Product_ImageFieldName)]
					Image Product_Image  {get; set;}
			
			
					/// <summary>
					/// The Product Name field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 8a69926f-388a-4296-83a6-454c1fb2359d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IProduct_DetailsConstants.Product_NameFieldName)]
					string Product_Name  {get; set;}
			
			
					/// <summary>
					/// The Shade Selection field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 5972527d-0e03-4f55-9bc4-9b707896a1c2</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IProduct_DetailsConstants.Shade_SelectionFieldName)]
					string Shade_Selection  {get; set;}
			
			
	}


	public static partial class IProduct_DetailsConstants{

			public const string TemplateIdString = "13cf5071-f642-4639-aec7-b45a29c939c4";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Product Details";

		
			
			public static readonly ID Bagel_FunctionFieldId = new ID("b9c46a24-959a-41fd-a697-65c341a132f1");
			public const string Bagel_FunctionFieldName = "Bagel Function";
			
		
			
			public static readonly ID DescriptionFieldId = new ID("0f663071-efe6-4c41-b09b-ff5137d7b379");
			public const string DescriptionFieldName = "Description";
			
		
			
			public static readonly ID Extra_LiftFieldId = new ID("e7971b67-73c0-4bf3-a3fd-d2a85a226ef7");
			public const string Extra_LiftFieldName = "Extra Lift";
			
		
			
			public static readonly ID Product_ImageFieldId = new ID("db0e3e15-dc51-4075-865a-0084c20c854d");
			public const string Product_ImageFieldName = "Product Image";
			
		
			
			public static readonly ID Product_NameFieldId = new ID("8a69926f-388a-4296-83a6-454c1fb2359d");
			public const string Product_NameFieldName = "Product Name";
			
		
			
			public static readonly ID Shade_SelectionFieldId = new ID("5972527d-0e03-4f55-9bc4-9b707896a1c2");
			public const string Shade_SelectionFieldName = "Shade Selection";
			
			

	}

	
	/// <summary>
	/// Product_Details
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/TresDivas/Modules/Product Details</para>	
	/// <para>ID: 13cf5071-f642-4639-aec7-b45a29c939c4</para>	
	/// </summary>
	[SitecoreType(TemplateId=IProduct_DetailsConstants.TemplateIdString)] //, Cachable = true
	public partial class Product_Details  : GlassBase, IProduct_Details
	{
	   
		
				/// <summary>
				/// The Bagel Function field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: b9c46a24-959a-41fd-a697-65c341a132f1</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IProduct_DetailsConstants.Bagel_FunctionFieldName)]
				public virtual string Bagel_Function  {get; set;}
					
		
				/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 0f663071-efe6-4c41-b09b-ff5137d7b379</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IProduct_DetailsConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
		
				/// <summary>
				/// The Extra Lift field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: e7971b67-73c0-4bf3-a3fd-d2a85a226ef7</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IProduct_DetailsConstants.Extra_LiftFieldName)]
				public virtual string Extra_Lift  {get; set;}
					
		
				/// <summary>
				/// The Product Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: db0e3e15-dc51-4075-865a-0084c20c854d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IProduct_DetailsConstants.Product_ImageFieldName)]
				public virtual Image Product_Image  {get; set;}
					
		
				/// <summary>
				/// The Product Name field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 8a69926f-388a-4296-83a6-454c1fb2359d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IProduct_DetailsConstants.Product_NameFieldName)]
				public virtual string Product_Name  {get; set;}
					
		
				/// <summary>
				/// The Shade Selection field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 5972527d-0e03-4f55-9bc4-9b707896a1c2</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IProduct_DetailsConstants.Shade_SelectionFieldName)]
				public virtual string Shade_Selection  {get; set;}
					
			
	}

}
namespace TresDivas.Website.Models.sitecore.templates.Project.TresDivas.Pages
{


 	/// <summary>
	/// IProduct_Detail Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/TresDivas/Pages/Product Detail</para>	
	/// <para>ID: dd18839a-0567-484a-ae3b-0407e6c4c336</para>	
	/// </summary>
	[SitecoreType(TemplateId=IProduct_DetailConstants.TemplateIdString )] //, Cachable = true
	public partial interface IProduct_Detail : IGlassBase 
	{
			
	}


	public static partial class IProduct_DetailConstants{

			public const string TemplateIdString = "dd18839a-0567-484a-ae3b-0407e6c4c336";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Product Detail";

			

	}

	
	/// <summary>
	/// Product_Detail
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/TresDivas/Pages/Product Detail</para>	
	/// <para>ID: dd18839a-0567-484a-ae3b-0407e6c4c336</para>	
	/// </summary>
	[SitecoreType(TemplateId=IProduct_DetailConstants.TemplateIdString)] //, Cachable = true
	public partial class Product_Detail  : GlassBase, IProduct_Detail
	{
	   
			
	}

}
namespace TresDivas.Website.Models.sitecore.templates.Project.TresDivas.Pages
{


 	/// <summary>
	/// IHome Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/TresDivas/Pages/Home</para>	
	/// <para>ID: e90f7bd6-1ebc-4356-ad1c-8f5a4b6c6440</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomeConstants.TemplateIdString )] //, Cachable = true
	public partial interface IHome : IGlassBase 
	{
			
	}


	public static partial class IHomeConstants{

			public const string TemplateIdString = "e90f7bd6-1ebc-4356-ad1c-8f5a4b6c6440";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Home";

			

	}

	
	/// <summary>
	/// Home
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/TresDivas/Pages/Home</para>	
	/// <para>ID: e90f7bd6-1ebc-4356-ad1c-8f5a4b6c6440</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomeConstants.TemplateIdString)] //, Cachable = true
	public partial class Home  : GlassBase, IHome
	{
	   
			
	}

}
